### ISSUE TITLE
no access to gitlab.sba-research.org

### ISSUE THREAD

**Issue by frakman1** [fabiansteiner/dtb_finder#1]
I have a working instance of the FACT webapp docker container and tried to install this plugin within the `/opt/FACT_core/src/plugins/analysis/` folder.
However, the command:
```
git submodule add https://gitlab.sba-research.org/autohoney-i-iot/processor-database/dtb_finder.git src/plugins/analysis/dtb_finder
```
Won't work since I don't have access to that repo.

```bash
fact@Kubuntu18:/opt/FACT_core/src/plugins/analysis/dtb_finder$ ls -lasth
total 44K
4.0K drwxr-xr-x 3 fact fact 4.0K Nov  3 17:51 code
4.0K drwxr-xr-x 8 fact fact 4.0K Nov  2 14:24 .
4.0K drwxr-xr-x 8 fact fact 4.0K Nov  2 14:24 .git
4.0K drwxr-xr-x 2 fact fact 4.0K Nov  2 14:24 view
4.0K -rw-r--r-- 1 fact fact  722 Nov  2 14:24 README.md
   0 -rw-r--r-- 1 fact fact    0 Nov  2 14:24 __init__.py
4.0K -rwxr-xr-x 1 fact fact  351 Nov  2 14:24 install.sh
4.0K drwxr-xr-x 2 fact fact 4.0K Nov  2 14:24 restaccess
4.0K drwxr-xr-x 2 fact fact 4.0K Nov  2 14:24 signatures
4.0K drwxr-xr-x 2 fact fact 4.0K Nov  2 14:24 test_files
8.0K drwxr-xr-x 1 fact fact 4.0K Nov  2 14:24 ..
fact@Kubuntu18:/opt/FACT_core/src/plugins/analysis/dtb_finder$ git submodule add https://gitlab.sba-research.org/autohoney-i-iot/processor-database/dtb_finder.git src/plugins/analysis/dtb_finder
Cloning into '/opt/FACT_core/src/plugins/analysis/dtb_finder/src/plugins/analysis/dtb_finder'...
Username for 'https://gitlab.sba-research.org': frakman1
Password for 'https://frakman1@gitlab.sba-research.org':
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.sba-research.org/autohoney-i-iot/processor-database/dtb_finder.git/'
fatal: clone of 'https://gitlab.sba-research.org/autohoney-i-iot/processor-database/dtb_finder.git' into submodule path '/opt/FACT_core/src/plugins/analysis/dtb_finder/src/plugins/analysis/dtb_finder' failed
```

This project/repo was brought up as part of this discussion in the FACT issues page:
https://github.com/fkie-cad/FACT_core/issues/675#issuecomment-970356014

**Comment by fabiansteiner** [comment]
sorry, cloned the repo from another repo and forgot to change the link. This problem should be solved.

**Comment by frakman1** [comment]
I am still unable to get this plugin to work.
This is the folder structure within the FACT docker container 

```
fact@Kubuntu18:/opt/FACT_core/src/plugins/analysis$ tree dtb_finder/
dtb_finder/
|-- README.md
|-- __init__.py
|-- code
|   |-- __init__.py
|   |-- __pycache__
|   |   `-- dtb_finder.cpython-38.pyc
|   `-- dtb_finder.py
|-- install.sh
|-- restaccess
|   `-- get_dtbs.py
|-- signatures
|   `-- devicetree.yara
|-- test_files
|   |-- DeviceTree.zip
|   `-- ddwrt-linksys-wrt1900acs-webflash.bin
`-- view
    `-- dtb_finder.html
```

I went into `/opt/FACT_core/src` folder and ran `./install.py -B`
I then restarted the FACT container.
Althought I see the "dtb finder" tab in the WebUI left frame, I see no results when I click on it

I see this error in the logs:

```
[pid: 431|app: 0|req: 4/28] 192.168.86.31 () {34 vars in 986 bytes} [Tue Nov 30 16:41:52 2021] GET /analysis/f0ff064c91b9ba52d75c2364b6fa30445e99f9725cb62156b161fc536454c660_33623/dtb_finder/ro/throbber.gif => generated 52764 bytes in 544 msecs (HTTP/1.1 200) 4 headers in 226 bytes (1 switches on core 0)
[pid: 425|app: 0|req: 6/29] 192.168.86.31 () {34 vars in 978 bytes} [Tue Nov 30 16:41:53 2021] GET /analysis/f0ff064c91b9ba52d75c2364b6fa30445e99f9725cb62156b161fc536454c660_33623/dtb_finder/ro/32px.png => generated 52644 bytes in 548 msecs (HTTP/1.1 200) 4 headers in 226 bytes (1 switches on core 0)
[pid: 427|app: 0|req: 7/30] 192.168.86.31 () {44 vars in 1247 bytes} [Tue Nov 30 16:42:09 2021] POST /analysis/f0ff064c91b9ba52d75c2364b6fa30445e99f9725cb62156b161fc536454c660_33623/dtb_finder/ro/None => generated 404 bytes in 89 msecs (HTTP/1.1 302) 5 headers in 357 bytes (1 switches on core 1)
[pid: 427|app: 0|req: 8/31] 192.168.86.31 () {38 vars in 1107 bytes} [Tue Nov 30 16:42:09 2021] GET /analysis/f0ff064c91b9ba52d75c2364b6fa30445e99f9725cb62156b161fc536454c660_33623/dtb_finder/ro/None => generated 52524 bytes in 537 msecs (HTTP/1.1 200) 4 headers in 226 bytes (1 switches on core 0)
Process ExceptionSafeProcess-15:2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/FACT_core/src/helperFunctions/process.py", line 57, in run
    raise exception
  File "/opt/FACT_core/src/helperFunctions/process.py", line 52, in run
    Process.run(self)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/FACT_core/src/analysis/PluginBase.py", line 123, in process_next_object
    finished_task = self.analyze_file(task)
  File "/opt/FACT_core/src/analysis/PluginBase.py", line 69, in analyze_file
    fo = self.process_object(file_object)
  File "/opt/FACT_core/src/plugins/analysis/dtb_finder/code/dtb_finder.py", line 79, in process_object
    parentAnalysis = parent.processed_analysis[self.NAME]
KeyError: 'dtb_finder'
[2021-11-30 16:42:09][PluginBase][ERROR]: Worker 0: Exception during analysis dtb_finder on f0ff064c91b9ba52d75c2364b6fa30445e99f9725cb62156b161fc536454c660_33623
```

![image](https://user-images.githubusercontent.com/5826484/144090170-d9c5e756-0b6e-4219-8806-49c5df1469c3.png)
